apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-cloudwatch-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  cloudwatch-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: CloudWatch
        type: cloudwatch
        uid: cloudwatch
        access: proxy
        jsonData:
          authType: keys
          defaultRegion: us-east-1
        secureJsonData:
          accessKey: "$AWS_ACCESS_KEY_ID"
          secretKey: "$AWS_SECRET_ACCESS_KEY"
