apiVersion: apps/v1
kind: Deployment
metadata:
  name: pve-exporter
  namespace: monitoring
  labels:
    app: pve-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pve-exporter
  template:
    metadata:
      labels:
        app: pve-exporter
    spec:
      containers:
        - name: pve-exporter
          image: prompve/prometheus-pve-exporter
          ports:
            - containerPort: 9221
              name: metrics
          envFrom:
            - secretRef:
                name: pve-exporter-credentials
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: pve-exporter
  namespace: monitoring
  labels:
    app: pve-exporter
spec:
  type: ClusterIP
  selector:
    app: pve-exporter
  ports:
    - port: 9221
      targetPort: metrics
      protocol: TCP
      name: metrics
